<template>
  <div class="footer">
    <div class="logo">
      <a href="https://myscreate.com/"><img src='../assets/logo.svg' alt="ma-ya's CREATE" rel="noopener"></a>
    </div>
    <small>© Copyright {{ getYear }} │ ma-ya's CREATE All rights reserved.<br>This has been generated by Vue.js.</small>
  </div>
</template>

<script>
export default {
  name: 'Footer',
  computed: {
    getYear(){
      return new Date().getFullYear();
    }
  }
}
</script>

<style scoped lang='scss'>

.footer {
  margin-bottom: 3rem;
  .logo {
    img {
      width: 70px;
      height: auto;
    }
  }
  small {
    font-size: .6rem;
  }
}
</style>
